name:                AR-SQL
version:             0.1.0.0
license:             MIT
author:             Sebastián Giulianelli
maintainer:         sebastiangiulianelli02@gmail.com

extra-source-files:
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- mysql-haskell ^>=1.1.4
- io-streams ^>=1.5.2.2
- text
- base ^>=4.16.4.0
- pretty
- array
- haskeline ^>= 0.8.2.1
- mtl
- exceptions
- QuickCheck
- containers
- bytestring >= 0.11.4.0
- network >= 3.1.2.9
- ansi-wl-pprint
- cassava
- vector >= 0.12.3.1
- directory >= 1.3.6.2


default-extensions:
- TupleSections
- MultiWayIf
- LambdaCase
- DataKinds
- PolyKinds
- FlexibleInstances
- FlexibleContexts

library:
  source-dirs: 
  - src
  exposed-modules:
  - TableOperators
  - Common
  - PrettyPrinter
  - Simplytyped
  - Parse 
  - Csv
  - Error
  - Mysql

executables:
  AR-SQL:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - happy
    dependencies:
      - AR-SQL